services:
  postgres:
    image: postgres:16.3-alpine3.19
    container_name: postgres_api_dev
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - api
networks:
  api:
    driver: bridge

volumes:
  api_db_data:
